### ISSUE TITLE
リポジトリにハッシュタグをつける

### ISSUE THREAD

**Issue by am2525nyan** [ProgateHackathon/Gitagram#49]
# 概要
のちに検索できるようにするためにmodelに追加、リポジトリ追加画面にハッシュタグ。選択式？
## タスク

- [x] #53
- [x] #54
- [x] #55
- [x] #56

## 参考リンク

- [リンク名](url)

**Comment by am2525nyan** [comment]
@urassh 
product modelにハッシュタグつけたいのですが、firebaseにハッシュタグをstringとして入れるか、どこか別にハッシュタグモデルを作ってやるかどっちがいいと思いますか😭

**Comment by urassh** [comment]
@am2525nyan 
考えてみた結果、ハッシュタグモデルを作るのが一番良いと思います！
これ関係のModelやDBの工事も含めて俺も手伝ったほうが良さそうな気がしたから一緒にやりたいかも！！
なので、時間作って相談したいー！

理由
1. これ関係のfirebaseのDBが3つになりそうだから
2. DBに保存する形式とアプリで使う形式を分ける必要がありそうだから

Productに関係するDB
1. **Product DB** (product_id: uuid, その他諸々)
2. **ハッシュタグ DB** (tag_id: uuid, tag_name: string)
3. **ハッシュタグ付きProduct DB**(product_id, tag_id)

こういう構成にすると、Product と ハッシュタグが独立して管理できるのと、ハッシュタグ付きProduct DB で結びつけられそう！！

**Comment by urassh** [comment]
実装イメージメモ
データモデル(DB)
- Product(id: uuid, content: string, developer_id: uuid)
- HashTag(id: uuid, content: string)
- HashTagToProduct(id: uuid, product_id: uuid, hastag_id: uuid)

データモデル(アプリ)
- Product(id: ID, content: string, developer: Developer, hashTags: [HashTag], product_image: UIImage)
- HashTag(id: HasTagID, content: string)

実装流れ。(投稿)
1. Productは複数のHashTagを持っている。
2. 投稿する時はProductのFirebaseに保存。
3. HashTagを全てHashTagのFirebaseに保存。
4. product_id と hash_tag_id は HashTagToProductのFirebaseに保存。

実装流れ。(取得)
1. Product(Firebase)から、保存されているProductのデータを取得。
2. それぞれのproduct_idからHashTagToProduct(Firebase)でProductの持っているHashTagのidを知る。
3. HashTagのidからHashTag(Firebase)を取ってきて、　Product(アプリ)のhashTags配列に入れる。
4. これを1Productづつ繰り返す。

**Comment by am2525nyan** [comment]
@urassh 
一緒にやりたいです！ハッシュタグ選択式にするか、自分で打たせるかにもよりますよね😭
流れありがとうございます！！！めちゃめちゃわかりやすいです！
